version: '3.8'

services:
  streamyfin-discord-bot:
    image: retardgerman/streamyfin-discord-bot:latest
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped