name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/discord-bot:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image with version tag
      run: |
        IMAGE_VERSION=$(date +'%Y%m%d%H%M%S') 
        docker tag ${{ secrets.DOCKER_USERNAME }}/discord-bot:latest ${{ secrets.DOCKER_USERNAME }}/discord-bot:${IMAGE_VERSION}
        docker push ${{ secrets.DOCKER_USERNAME }}/discord-bot:${IMAGE_VERSION}
 
